<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="demployementEcoreMetaModel" nsURI="http://www.example.org/demployementEcoreMetaModel"
    nsPrefix="demployementEcoreMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="DeployementModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="-1"
        eType="#//Artifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationpath" upperBound="-1"
        eType="#//CommunicationPath" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploy" upperBound="-1"
        eType="#//Deploy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityproperties" upperBound="-1"
        eType="#//SecurityProperties" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameNode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameArtifact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameDevice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deploy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" eType="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameDeploy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="2"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="integrity" eType="#//Integrity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secrecy" eType="#//Secrecy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="#//Call"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameAssociation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationPath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="2" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" eType="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internet" eType="#//Internet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encrypted" eType="#//Encrypted"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NamePathComm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Integrity" eSuperTypes="#//SecurityProperties"/>
  <eClassifiers xsi:type="ecore:EClass" name="Secrecy" eSuperTypes="#//SecurityProperties"/>
  <eClassifiers xsi:type="ecore:EClass" name="Internet" eSuperTypes="#//SecurityProperties"/>
  <eClassifiers xsi:type="ecore:EClass" name="Encrypted" eSuperTypes="#//SecurityProperties"/>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//SecurityProperties"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityProperties"/>
</ecore:EPackage>
